version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
      - image: 'circleci/postgres:latest'
        environment:
          POSTGRES_HOST_AUTH_METHOD: "trust"
    steps:
      - checkout
      - run: npm install
      - run: npm start
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 120s
      - run:
          name: Server start
          command: npm start
          background: true
      - run: npm run test
